"""Initial migration with all tables

Revision ID: 4dc19ba2cc10
Revises: 659ee0e68777
Create Date: 2025-10-26 11:05:06.934564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc19ba2cc10'
down_revision: Union[str, None] = '659ee0e68777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_code', 'customers', ['code'], unique=False)
    op.create_index('ix_pack_unit_code', 'pack_units', ['code'], unique=False)
    op.create_index('ix_price_list_code', 'price_lists', ['code'], unique=False)
    op.create_index('ix_purchase_order_po_number', 'purchase_orders', ['po_number'], unique=False)
    op.create_index('ix_sales_order_so_number', 'sales_orders', ['so_number'], unique=False)
    op.create_index('ix_supplier_code', 'suppliers', ['code'], unique=False)
    op.create_index('ix_work_order_code', 'work_orders', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_order_code', table_name='work_orders')
    op.drop_index('ix_supplier_code', table_name='suppliers')
    op.drop_index('ix_sales_order_so_number', table_name='sales_orders')
    op.drop_index('ix_purchase_order_po_number', table_name='purchase_orders')
    op.drop_index('ix_price_list_code', table_name='price_lists')
    op.drop_index('ix_pack_unit_code', table_name='pack_units')
    op.drop_index('ix_customer_code', table_name='customers')
    # ### end Alembic commands ###
