"""add_finished_goods_and_movements

Revision ID: 01ad7dcb5179
Revises: 7c82aa02b929
Create Date: 2025-10-26 17:29:52.266811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01ad7dcb5179"
down_revision: Union[str, None] = "7c82aa02b929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finished_goods",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("base_unit", sa.String(length=10), nullable=False),
        sa.Column("formula_id", sa.String(length=36), nullable=True),
        sa.Column("formula_revision", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["formula_id"],
            ["formulas.id"],
            name=op.f("fk_finished_goods__formula_id__formulas"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finished_goods")),
    )
    op.create_index(
        op.f("ix_finished_goods_code"), "finished_goods", ["code"], unique=True
    )
    op.create_table(
        "finished_goods_inventory",
        sa.Column("fg_id", sa.String(length=36), nullable=False),
        sa.Column("soh", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["fg_id"],
            ["finished_goods.id"],
            name=op.f("fk_finished_goods_inventory__fg_id__finished_goods"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("fg_id", name=op.f("pk_finished_goods_inventory")),
    )
    op.create_table(
        "batch_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("material_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("qty_theoretical", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("qty_actual", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("cost_at_time", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
            name=op.f("fk_batch_lines__batch_id__batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["products.id"],
            name=op.f("fk_batch_lines__material_id__products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_lines")),
        sa.UniqueConstraint("batch_id", "material_id", name="uq_batch_line"),
    )
    op.create_index("ix_batch_line_batch", "batch_lines", ["batch_id"], unique=False)
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("item_type", sa.String(length=10), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("qty", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("source_batch_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_batch_id"],
            ["batches.id"],
            name=op.f("fk_inventory_movements__source_batch_id__batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
    )
    op.create_index(
        "ix_movements_batch", "inventory_movements", ["source_batch_id"], unique=False
    )
    op.create_index("ix_movements_date", "inventory_movements", ["date"], unique=False)
    op.create_index(
        "ix_movements_item",
        "inventory_movements",
        ["item_type", "item_id"],
        unique=False,
    )
    op.add_column(
        "batches", sa.Column("batch_status", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batches", "batch_status")
    op.drop_index("ix_movements_item", table_name="inventory_movements")
    op.drop_index("ix_movements_date", table_name="inventory_movements")
    op.drop_index("ix_movements_batch", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index("ix_batch_line_batch", table_name="batch_lines")
    op.drop_table("batch_lines")
    op.drop_table("finished_goods_inventory")
    op.drop_index(op.f("ix_finished_goods_code"), table_name="finished_goods")
    op.drop_table("finished_goods")
    # ### end Alembic commands ###
