"""add_product_type_flags_and_manufactured_cost_fields

Revision ID: 4c76f70220c2
Revises: a527ff0cfbcd
Create Date: 2025-11-02 18:50:16.692994

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c76f70220c2"
down_revision: Union[str, None] = "a527ff0cfbcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new product type flags and manufactured cost fields
    op.add_column("products", sa.Column("is_purchase", sa.Boolean(), nullable=True))
    op.add_column("products", sa.Column("is_sell", sa.Boolean(), nullable=True))
    op.add_column("products", sa.Column("is_assemble", sa.Boolean(), nullable=True))
    op.add_column(
        "products",
        sa.Column(
            "manufactured_cost_inc_gst",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "manufactured_cost_ex_gst", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "products",
        sa.Column("manufactured_tax_included", sa.String(length=1), nullable=True),
    )

    # Set defaults for existing products based on product_type
    op.execute(
        """
        UPDATE products
        SET is_purchase = CASE
            WHEN product_type = 'RAW' THEN 1
            ELSE 0
        END,
        is_sell = CASE
            WHEN product_type = 'FINISHED' THEN 1
            ELSE 0
        END,
        is_assemble = CASE
            WHEN product_type = 'WIP' THEN 1
            ELSE 0
        END
    """
    )

    # Set non-nullable defaults for new rows (SQLite Boolean is actually INTEGER 0/1)
    op.execute(
        "UPDATE products SET is_purchase = COALESCE(is_purchase, 0) WHERE is_purchase IS NULL"
    )
    op.execute(
        "UPDATE products SET is_sell = COALESCE(is_sell, 0) WHERE is_sell IS NULL"
    )
    op.execute(
        "UPDATE products SET is_assemble = COALESCE(is_assemble, 0) WHERE is_assemble IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "manufactured_tax_included")
    op.drop_column("products", "manufactured_cost_ex_gst")
    op.drop_column("products", "manufactured_cost_inc_gst")
    op.drop_column("products", "is_assemble")
    op.drop_column("products", "is_sell")
    op.drop_column("products", "is_purchase")
    # ### end Alembic commands ###
