"""extend_product_with_all_fields

Revision ID: 74980f3155d7
Revises: 01ad7dcb5179
Create Date: 2025-10-26 17:31:24.946929

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74980f3155d7"
down_revision: Union[str, None] = "01ad7dcb5179"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("ean13", sa.String(length=20), nullable=True))
    op.add_column(
        "products", sa.Column("supplier_id", sa.String(length=36), nullable=True)
    )
    op.add_column("products", sa.Column("size", sa.String(length=10), nullable=True))
    op.add_column(
        "products", sa.Column("base_unit", sa.String(length=10), nullable=True)
    )
    op.add_column("products", sa.Column("pack", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("dgflag", sa.String(length=1), nullable=True))
    op.add_column("products", sa.Column("form", sa.String(length=10), nullable=True))
    op.add_column("products", sa.Column("pkge", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("label", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("manu", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("taxinc", sa.String(length=1), nullable=True))
    op.add_column(
        "products", sa.Column("salestaxcde", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column("purcost", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("purtax", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("wholesalecost", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "products", sa.Column("disccdeone", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products", sa.Column("disccdetwo", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products", sa.Column("wholesalecde", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products", sa.Column("retailcde", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products", sa.Column("countercde", sa.String(length=1), nullable=True)
    )
    op.add_column("products", sa.Column("tradecde", sa.String(length=1), nullable=True))
    op.add_column(
        "products", sa.Column("contractcde", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products", sa.Column("industrialcde", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "products", sa.Column("distributorcde", sa.String(length=1), nullable=True)
    )
    # Note: SQLite doesn't support adding foreign key constraints via ALTER TABLE
    # Foreign key relationship is handled at the application level
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "distributorcde")
    op.drop_column("products", "industrialcde")
    op.drop_column("products", "contractcde")
    op.drop_column("products", "tradecde")
    op.drop_column("products", "countercde")
    op.drop_column("products", "retailcde")
    op.drop_column("products", "wholesalecde")
    op.drop_column("products", "disccdetwo")
    op.drop_column("products", "disccdeone")
    op.drop_column("products", "wholesalecost")
    op.drop_column("products", "purtax")
    op.drop_column("products", "purcost")
    op.drop_column("products", "salestaxcde")
    op.drop_column("products", "taxinc")
    op.drop_column("products", "manu")
    op.drop_column("products", "label")
    op.drop_column("products", "pkge")
    op.drop_column("products", "form")
    op.drop_column("products", "dgflag")
    op.drop_column("products", "pack")
    op.drop_column("products", "base_unit")
    op.drop_column("products", "size")
    op.drop_column("products", "supplier_id")
    op.drop_column("products", "ean13")
    # ### end Alembic commands ###
    op.drop_column("products", "industrialcde")
    op.drop_column("products", "contractcde")
    op.drop_column("products", "tradecde")
    op.drop_column("products", "countercde")
    op.drop_column("products", "retailcde")
    op.drop_column("products", "wholesalecde")
    op.drop_column("products", "disccdetwo")
    op.drop_column("products", "disccdeone")
    op.drop_column("products", "wholesalecost")
    op.drop_column("products", "purtax")
    op.drop_column("products", "purcost")
    op.drop_column("products", "salestaxcde")
    op.drop_column("products", "taxinc")
    op.drop_column("products", "manu")
    op.drop_column("products", "label")
    op.drop_column("products", "pkge")
    op.drop_column("products", "form")
    op.drop_column("products", "dgflag")
    op.drop_column("products", "pack")
    op.drop_column("products", "base_unit")
    op.drop_column("products", "size")
    op.drop_column("products", "supplier_id")
    op.drop_column("products", "ean13")
    # ### end Alembic commands ###
