"""add_legacy_acstk_data_table

Revision ID: 7c82aa02b929
Revises: 4dc19ba2cc10
Create Date: 2025-10-26 17:17:06.263947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c82aa02b929'
down_revision: Union[str, None] = '4dc19ba2cc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_acstk_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('legacy_no', sa.Integer(), nullable=True),
    sa.Column('legacy_search', sa.String(length=50), nullable=True),
    sa.Column('ean13', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('desc1', sa.String(length=50), nullable=True),
    sa.Column('desc2', sa.String(length=20), nullable=True),
    sa.Column('legacy_suplr', sa.String(length=10), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('legacy_unit', sa.String(length=10), nullable=True),
    sa.Column('pack', sa.Integer(), nullable=True),
    sa.Column('dgflag', sa.String(length=1), nullable=True),
    sa.Column('form', sa.String(length=10), nullable=True),
    sa.Column('pkge', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('manu', sa.Integer(), nullable=True),
    sa.Column('legacy_active', sa.String(length=1), nullable=True),
    sa.Column('taxinc', sa.String(length=1), nullable=True),
    sa.Column('salestaxcde', sa.String(length=1), nullable=True),
    sa.Column('purcost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purtax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wholesalecost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disccdeone', sa.String(length=1), nullable=True),
    sa.Column('disccdetwo', sa.String(length=1), nullable=True),
    sa.Column('wholesalecde', sa.String(length=1), nullable=True),
    sa.Column('retailcde', sa.String(length=1), nullable=True),
    sa.Column('countercde', sa.String(length=1), nullable=True),
    sa.Column('tradecde', sa.String(length=1), nullable=True),
    sa.Column('contractcde', sa.String(length=1), nullable=True),
    sa.Column('industrialcde', sa.String(length=1), nullable=True),
    sa.Column('distributorcde', sa.String(length=1), nullable=True),
    sa.Column('retail', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('counter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contract', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('industrial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distributor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suplr4stdcost', sa.String(length=10), nullable=True),
    sa.Column('search4stdcost', sa.String(length=50), nullable=True),
    sa.Column('cogs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rmc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gpr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('soh', sa.Integer(), nullable=True),
    sa.Column('sohv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sip', sa.Integer(), nullable=True),
    sa.Column('soo', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('legacy_date', sa.String(length=10), nullable=True),
    sa.Column('bulk', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lid', sa.Integer(), nullable=True),
    sa.Column('pbox', sa.Integer(), nullable=True),
    sa.Column('boxlbl', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_legacy_acstk_data__product_id__products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_acstk_data'))
    )
    op.create_index(op.f('ix_legacy_acstk_data_product_id'), 'legacy_acstk_data', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legacy_acstk_data_product_id'), table_name='legacy_acstk_data')
    op.drop_table('legacy_acstk_data')
    # ### end Alembic commands ###
