"""Add xero_account field to raw_materials

Revision ID: 7fe22ea20cea
Revises: b7a47f197d45
Create Date: 2025-10-26 20:34:27.057517

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe22ea20cea"
down_revision: Union[str, None] = "b7a47f197d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_materials", sa.Column("xero_account", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_materials", "xero_account")
    # ### end Alembic commands ###
